# Generated by Django 3.2 on 2021-05-14 11:53

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.IntegerField(unique=True, validators=[mainapp.models.validate_phone], verbose_name='Номер телефона')),
                ('self_invite_code', models.CharField(blank=True, max_length=6, unique=True, verbose_name='Ваш код')),
                ('other_invite_code', models.CharField(blank=True, max_length=6, validators=[mainapp.models.validate_code], verbose_name='Чужой код')),
                ('check_code', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'verbose_name': 'Пользователь',
            },
        ),
    ]
